"""empty message

Revision ID: 06093cb70d9d
Revises: 987cc7833fba
Create Date: 2022-05-26 14:56:24.363504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06093cb70d9d'
down_revision = '987cc7833fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
