"""empty message

Revision ID: 34035cc8077d
Revises: 744046ea5b85
Create Date: 2022-05-26 14:58:18.770055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34035cc8077d'
down_revision = '744046ea5b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('gender', sa.String(length=10), nullable=False))
    op.add_column('Users', sa.Column('preference', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'preference')
    op.drop_column('Users', 'gender')
    # ### end Alembic commands ###
