"""empty message

Revision ID: 987cc7833fba
Revises: 8b9f7eeacb09
Create Date: 2022-05-26 14:55:39.549590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987cc7833fba'
down_revision = '8b9f7eeacb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    # ### end Alembic commands ###
